### ISSUE TITLE
OpenSearch support

### ISSUE THREAD

**Issue by wizzwizz4** [freetonik/quickref.dev#12]
I'd love to be able to add this search engine to my browser easily. Please add [an OpenSearch schema and the corresponding `<link>` element](https://developer.mozilla.org/en-US/docs/Web/OpenSearch) so I can two-click add the search engine from the Firefox chrome.

**Comment by freetonik** [comment]
Done! Please check.

**Comment by wizzwizz4** [comment]
Brilliant, thanks! WOMM.
