### ISSUE TITLE
quickref.dev appears to be down

### ISSUE THREAD

**Issue by aterweele** [freetonik/quickref.dev#39]
Hi @freetonik , [seems like quickref.dev is down](https://downforeveryoneorjustme.com/quickref.dev). Not sure if you're not hosting it anymore or if there's a technical issue. Either way, I did really enjoy the service, thanks for creating it!

**Comment by freetonik** [comment]
Hi,
I'm afraid I had to [shut it down](https://rakhim.org/im-shutting-down-most-projects/).

**Comment by RoyiAvital** [comment]
May I ask why?
You made such an amazing sites and services.

**Comment by freetonik** [comment]
This particular project was pretty costly to run for a hobby project, and I couldn't find the energy to monetize it properly.
