### ISSUE TITLE
Add tags escaping

### ISSUE THREAD

**Issue by igoradamenko** [freetonik/quickref.dev#8]
Hey Rakhim!

I've just tried your new project and found a bug, I think. Not sure that here's a right place to fill bug reports, but anyway.

It looks like your rendering engine doesn't escape tags when they present in search results.

I don't know why, but the first search request I made was “[react-dev](https://quickref.dev/search?q=react-dev&type=all)”. One of the links there is `Creating a Dynamic <select> Menu with React`. Here's the result:

<img width="1274" alt="Screen Shot 2020-05-19 at 20 34 57" src="https://user-images.githubusercontent.com/6537798/82359187-3fdfb080-9a10-11ea-9dd8-a1263d01e11a.png">

**Comment by freetonik** [comment]
Hey!

Thanks for reporting this! I believe I just fixed it, please verify if you can.

**Comment by igoradamenko** [comment]
Yep, works fine now. Thanks!
